import { NextUIProvider } from "@nextui-org/react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MyNavbar from "../app/components/Navbar";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <NextUIProvider>
          <MyNavbar />
          {children}
        </NextUIProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
